const strings = {
    introductory_instructions: "Пиши здесь что делал и будешь делать. Без воды! :) \nСначала напиши только то, что уже сделал. Одним сообщением.",
    error_msg: "Возникла ошибка, попробуй позже",
    command_not_available: "Вам не доступна эта команда",
    ups: "Упс 😯. Что то пошло не так",
    great_Now_write_what_you_will_do: "Отлично! Теперь напиши что будешь делать.",
    super_your_daily_has_been_recorded: "Супер! Твой дейлик записан.",
    didnt_do_anything: "Ничего не сделал",
    it_seems_you_already_posted_here_today: "Кажется ты уже отписывал сегодня сюда 🤨",
    and_it_wont_be_possible_to_change_everything: "А все уже поменять дейлик не получится 😛",
    did_you_do_anything_else: "Ещё что то сделал? 🤔",
    post_on_this_topic_tomorrow: "Отпиши по этой теме завтра 🥱",
    haven_t_written_anything_yet_today: "Сегодня еще ничего не писал",
    empty: "Пусто",
    do_you_think_messages_appear_here_on_their_own: "Думаешь сообщения сами тут появляются? \nИх нужно писать!",
    it_seems_you_haven_t_posted_a_message_today_yet: "Кажется вы еще не оставляли дейлик сегодня",
    send_a_message_and_it_will_be_added_here: "Отправь сообщения и оно добавится сюда",
    soLittle: "Так мало?🧐 \nНапиши побольше текста.\nА то стыдно...",
    soLong: "К чему многословность?🧐 \nНапиши короче. \nА то читать устану...",
    it_seems_no_one_has_posted_any_tasks_today: "Кажется на сегодня никто не отписал по задачам",
    everybody_put_the_bolt: "Все положили болт",
    is_empty_everyone_s_still_sleeping: "Пусто... Все еще спят... 😴",
    kozhegu1ov: "@kozhegu1ov эт экс лид. Может он знает почему тут пусто 🤔",
    congratulation: "Поздравляю товарищи! Все заполнили дейлик вовремя",
    please_write_down_the_daily: "Отпиши дейлик плс",
    daily: "Дейлик!!!",
    wakeup: "Проснись и пой!",
    work_is_not_wolf: "Работа не волк... Работа ворк... А волк это гулять...",
    write_anything: "Черкани ченить",
    you_are_not_in_the_system: "Вас нет в системе. Отправьте боту текущие задачи для регистрации в системе",
    you_do_not_have_access_to_this_bot:  "У вас нет доступа к данному боту",
    can_only_be_used_in_groups: "Можно использовать только в группах",
    bugOnProd: "Баг на проде!!!",
    bugOnPreProd: "Баг на препроде!!!",
    daily_deleted_successfully: "Дейлик успешно удален! Теперь можешь написать новый.",
    no_daily_to_delete: "У тебя нет дейлика для удаления сегодня.",
    cannot_delete_after_report: "Нельзя удалить дейлик после отправки отчета в группу.",
    daily_deleted_but_report_sent: "Дейлик удален, но отчет уже был отправлен в группу.",
    cannot_edit_after_report: "Нельзя редактировать дейлик после отправки отчета в группу.",
    no_daily_to_edit: "У тебя нет дейлика для редактирования сегодня.",
    edit_select_part: "Выбери, что именно ты хочешь изменить:",
    edit_enter_yesterday: "📝 Отправь новый текст для <b>«Что делал»</b> (одним сообщением):",
    edit_enter_today: "📝 Отправь новый текст для <b>«Что буду делать»</b> (одним сообщением):",
    edit_both_step1: "🔄 <b>Шаг 1 из 2:</b> Отправь новый текст для <b>«Что делал»</b>:",
    edit_both_step2: "🔄 <b>Шаг 2 из 2:</b> Отлично! Теперь отправь новый текст для <b>«Что буду делать»</b>:",
    edit_yesterday_success: "Раздел «Что делал» успешно обновлен! ✅",
    edit_today_success: "Раздел «Что буду делать» успешно обновлен! ✅",
    edit_both_success: "Дейлик успешно обновлен! ✅",
    edit_cancelled: "Редактирование отменено.",
    daily_already_submitted_with_actions: "Ты уже заполнил дейлик на сегодня.\nЕсли хочешь внести изменения, нажми кнопку ниже или используй команду /edit_daily.",
};

export default strings;
